Groupement Citoyen/Models/Produit.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Groupement_Citoyen.Models
{
    public class Produit
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nom { get; set; }
        [Range(0, 100)]
        [Required]
        [DisplayName("Quantité")]
        public int Quantite { get; set; } = 0;
        [Range(0.01, 1000.00)]
        [Required]
        [DataType(DataType.Currency)]
        public decimal Prix { get; set; } = 0;
        public string Description { get; set; }
        public bool Visible { get; set; } = true;
        public Utilisateur Producteur { get; set; }
    }
}

Groupement Citoyen/Controllers/CommandesController.cs
using Groupement_Citoyen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Groupement_Citoyen.Controllers
{
    [Authorize(Roles ="Utilisateur")]
    public class CommandesController : Controller
    {
        private readonly GroupementCitoyenDbContext _context;
        private readonly UserManager<Utilisateur> _userManager;

        public CommandesController(GroupementCitoyenDbContext context, UserManager<Utilisateur> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Commandes
        public async Task<IActionResult> Index()
        {
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            ViewBag.userId = idUtilisateur;
            Utilisateur utilisateur = await _context.Utilisateurs.Where(u => u.Id.Equals(idUtilisateur)).Include(u => u.Commandes).ThenInclude(c => c.DetailsCommandes).ThenInclude(dc => dc.Produit).FirstAsync();
            if (utilisateur.Commandes.Count == 0)
            {
                utilisateur.Commandes.Add(new Commande());
                _context.Add(utilisateur.Commandes.Last());
                await _context.SaveChangesAsync();

            }
            utilisateur.Commandes.Last().CalculerTotal();
            _context.Update(utilisateur.Commandes.Last());
            await _context.SaveChangesAsync();
            return View(utilisateur);
        }

        // GET: Commandes/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var commande = await _context.Commandes
                 .Include(c => c.DetailsCommandes)
                 .ThenInclude(dc => dc.Produit)
                 .ThenInclude(p => p.Producteur)
                 .FirstOrDefaultAsync(m => m.Id == id);

            commande.CalculerTotal();
            _context.Update(commande);
            await _context.SaveChangesAsync();

            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // GET: Commandes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Commandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateAchat,Total")] Commande commande)
        {
            if (ModelState.IsValid)
            {
                _context.Add(commande);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(commande);
        }

        // POST: Commandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValiderCommande()
        {
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            Utilisateur u = await _context.Utilisateurs.Where(u => u.Id.Equals(idUtilisateur))
                .Include(u => u.Commandes)
                .ThenInclude(c => c.DetailsCommandes)
                .ThenInclude(dc => dc.Produit)
                .FirstAsync();
            u.PayerCommande();
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Commandes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjouterProduit(int quantite, int idProduit)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string idUtilisateur = _userManager.GetUserId(HttpContext.User);
                    var produit = await _context.Produits
                .FirstOrDefaultAsync(m => m.Id == idProduit);
                    var commande = await _context.Commandes.Where(c => c.Utilisateur.Id.Equals(idUtilisateur) && !c.Valider).Include(dc => dc.DetailsCommandes).ThenInclude(dc => dc.Produit).FirstAsync();
                    commande.AjouterProduit(produit, quantite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    throw;

                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Commandes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _context.Commandes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // POST: Commandes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commande = await _context.Commandes.FindAsync(id);
            _context.Commandes.Remove(commande);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommandeExists(int id)
        {
            return _context.Commandes.Any(e => e.Id == id);
        }
    }
}

Groupement Citoyen/Controllers/ProduitsController.cs
using Groupement_Citoyen.Models;
using Groupement_Citoyen.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Groupement_Citoyen.Controllers
{
    [Authorize(Roles ="Utilisateur, Producteur")]
    public class ProduitsController : Controller
    {
        private readonly GroupementCitoyenDbContext _context;
        private readonly UserManager<Utilisateur> _userManager;
        public ProduitsController(GroupementCitoyenDbContext context, UserManager<Utilisateur> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: Produits
        public async Task<IActionResult> Index(string idProducteur)
        {
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            Utilisateur utilisateur = await _userManager.FindByIdAsync(idUtilisateur);
            var roles = await _userManager.GetRolesAsync(utilisateur);
            if (roles.First().Contains("Producteur"))
            {
                return View(await _context.Produits.Include(p => p.Producteur).Where(p => p.Producteur.Id.Equals(idUtilisateur)).ToListAsync());
            }
            ViewBag.userId = idUtilisateur;
            if (idProducteur != null)
                return View(await _context.Produits.Include(p => p.Producteur).Where(p => p.Producteur.Id.Equals(idProducteur) && p.Visible).ToListAsync());
            return View(await _context.Produits.Include(p => p.Producteur).Where(p => p.Visible).ToListAsync());
        }

        // GET: Produits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // GET: Produits/Create
        public async Task<IActionResult> Create()
        {
            ProduitCreationVM vm = new ProduitCreationVM()
            {
                Produit = new Produit(),
                Producteur = await _context.Utilisateurs.FirstOrDefaultAsync()
            };
            return View(vm);
        }

        // POST: Produits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nom,Quantite,Prix,Description,Visible")] Produit produit)
        {
            string idProduteur = _userManager.GetUserId(HttpContext.User);
            produit.Producteur = await _context.Utilisateurs.Where(u => u.Id.Equals(idProduteur)).FirstAsync();
            if (ModelState.IsValid)
            {
                _context.Add(produit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Quantite,Prix,Description,Visible")] Produit produit)
        {
            if (id != produit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produit = await _context.Produits.FindAsync(id);
            _context.Produits.Remove(produit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduitExists(int id)
        {
            return _context.Produits.Any(e => e.Id == id);
        }
    }
}

Groupement Citoyen/Views/Produits/Create.cshtml
@model Groupement_Citoyen.ViewModel.ProduitCreationVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Produit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Produit.Nom" class="control-label"></label>
                <input asp-for="Produit.Nom" class="form-control" />
                <span asp-validation-for="Produit.Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Produit.Quantite" class="control-label"></label>
                <input asp-for="Produit.Quantite" class="form-control" />
                <span asp-validation-for="Produit.Quantite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Produit.Prix" class="control-label"></label>
                <input asp-for="Produit.Prix" class="form-control" />
                <span asp-validation-for="Produit.Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Produit.Description" class="control-label"></label>
                <input asp-for="Produit.Description" class="form-control" />
                <span asp-validation-for="Produit.Description" class="text-danger"></span>
            </div>
            <table>
                <th>
                    @Html.DisplayNameFor(model => model.Producteur.Nom)
                </th>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.Producteur.Nom)
                </td>
            </table>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Groupement Citoyen/Views/Produits/Delete.cshtml
@model Groupement_Citoyen.Models.Produit

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prix)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Visible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Visible)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Groupement Citoyen/Views/Produits/Details.cshtml
@model Groupement_Citoyen.Models.Produit

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produit</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantite)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantite)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prix)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prix)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Visible)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Visible)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Groupement Citoyen/Views/Produits/Edit.cshtml
@model Groupement_Citoyen.Models.Produit

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produit</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantite" class="control-label"></label>
                <input asp-for="Quantite" class="form-control" />
                <span asp-validation-for="Quantite" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prix" class="control-label"></label>
                <input asp-for="Prix" class="form-control" />
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Visible" /> @Html.DisplayNameFor(model => model.Visible)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Groupement Citoyen/Views/Produits/Index.cshtml
@model IEnumerable<Groupement_Citoyen.Models.Produit>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    @if (this.User.IsInRole("Producteur"))
    {
        <a asp-action="Create">Create New</a>
    }
    </p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prix)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            @if (this.User.IsInRole("Producteur"))
            {
                <th>
                    @Html.DisplayNameFor(model => model.Visible)
                </th>
            }
                <th>
                    @Html.DisplayNameFor(model => model.Producteur)
                </th>
                <th></th>
            </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            @if (this.User.IsInRole("Producteur"))
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Visible)
                </td>
            }
                <td>
                    @Html.DisplayFor(modelItem => item.Producteur.NomComplet)
                </td>
                <td>
                    @if (this.User.IsInRole("Producteur"))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    }
                    @if (this.User.IsInRole("Utilisateur") && item.Quantite > 0)
                    {
                        <form asp-action="AjouterProduit" asp-controller="Commandes" asp-route-idUtilisateur="@ViewBag.userId" asp-route-idProduit="@item.Id">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <div class="input-group input-group-sm mb-3">
                                    <div class="input-group-prepend">
                                        <span class="input-group-text" id="inputGroup-sizing-sm">Quantité</span>
                                    </div>
                                    <input type="number" name="quantite" class="form-control" aria-label="Small" aria-describedby="inputGroup-sizing-sm">
                                </div>
                                <input type="submit" value="Ajouter au panier" class="btn btn-outline-primary" />
                            </div>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>