Groupement Citoyen/Models/Commande.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Groupement_Citoyen.Models
{
    public class Commande
    {
        [Key]
        public int Id { get; set; }
        [DataType(DataType.Date)]
        [DisplayName("Date d'achat")]
        public DateTime DateAchat { get; set; } = DateTime.Now;
        [DataType(DataType.Currency)]
        public decimal Total { get; set; }
        public List<DetailsCommande> DetailsCommandes { get; set; } = new List<DetailsCommande>() { };
        public bool Valider { get; set; } = false;
        public Utilisateur Utilisateur { get; set; }
        public void CalculerTotal()
        {
            Total = 0;
            foreach (DetailsCommande detailsCommande in DetailsCommandes)
            {
                Total += detailsCommande.Produit.Prix * detailsCommande.Quantite;
            }
        }

        public void AjouterProduit(Produit produit, int quantite)
        {
            if (produit.Quantite < quantite)
            {
                throw QuantiteInsuffisante();
            }
            DetailsCommandes.Add(new DetailsCommande(produit, quantite, this));
            CalculerTotal();
        }

        private Exception QuantiteInsuffisante()
        {
            throw new NotImplementedException();
        }
    }
}

Groupement Citoyen/Controllers/CommandesController.cs
using Groupement_Citoyen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Groupement_Citoyen.Controllers
{
    [Authorize(Roles ="Utilisateur")]
    public class CommandesController : Controller
    {
        private readonly GroupementCitoyenDbContext _context;
        private readonly UserManager<Utilisateur> _userManager;

        public CommandesController(GroupementCitoyenDbContext context, UserManager<Utilisateur> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Commandes
        public async Task<IActionResult> Index()
        {
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            ViewBag.userId = idUtilisateur;
            Utilisateur utilisateur = await _context.Utilisateurs.Where(u => u.Id.Equals(idUtilisateur)).Include(u => u.Commandes).ThenInclude(c => c.DetailsCommandes).ThenInclude(dc => dc.Produit).FirstAsync();
            if (utilisateur.Commandes.Count == 0)
            {
                utilisateur.Commandes.Add(new Commande());
                _context.Add(utilisateur.Commandes.Last());
                await _context.SaveChangesAsync();

            }
            utilisateur.Commandes.Last().CalculerTotal();
            _context.Update(utilisateur.Commandes.Last());
            await _context.SaveChangesAsync();
            return View(utilisateur);
        }

        // GET: Commandes/Details/5
        public async Task<IActionResult> Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            var commande = await _context.Commandes
                 .Include(c => c.DetailsCommandes)
                 .ThenInclude(dc => dc.Produit)
                 .ThenInclude(p => p.Producteur)
                 .FirstOrDefaultAsync(m => m.Id == id);

            commande.CalculerTotal();
            _context.Update(commande);
            await _context.SaveChangesAsync();

            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // GET: Commandes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Commandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DateAchat,Total")] Commande commande)
        {
            if (ModelState.IsValid)
            {
                _context.Add(commande);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(commande);
        }

        // POST: Commandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ValiderCommande()
        {
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            Utilisateur u = await _context.Utilisateurs.Where(u => u.Id.Equals(idUtilisateur))
                .Include(u => u.Commandes)
                .ThenInclude(c => c.DetailsCommandes)
                .ThenInclude(dc => dc.Produit)
                .FirstAsync();
            u.PayerCommande();
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: Commandes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjouterProduit(int quantite, int idProduit)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string idUtilisateur = _userManager.GetUserId(HttpContext.User);
                    var produit = await _context.Produits
                .FirstOrDefaultAsync(m => m.Id == idProduit);
                    var commande = await _context.Commandes.Where(c => c.Utilisateur.Id.Equals(idUtilisateur) && !c.Valider).Include(dc => dc.DetailsCommandes).ThenInclude(dc => dc.Produit).FirstAsync();
                    commande.AjouterProduit(produit, quantite);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {

                    throw;

                }
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: Commandes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var commande = await _context.Commandes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (commande == null)
            {
                return NotFound();
            }

            return View(commande);
        }

        // POST: Commandes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var commande = await _context.Commandes.FindAsync(id);
            _context.Commandes.Remove(commande);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CommandeExists(int id)
        {
            return _context.Commandes.Any(e => e.Id == id);
        }
    }
}

Groupement Citoyen/Controllers/DetailsCommandesController.cs
using Groupement_Citoyen.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Groupement_Citoyen.Controllers
{
    [Authorize(Roles ="Utilisateur")]
    public class DetailsCommandesController : Controller
    {
        private readonly GroupementCitoyenDbContext _context;
        private readonly UserManager<Utilisateur> _userManager;
        public DetailsCommandesController(GroupementCitoyenDbContext context, UserManager<Utilisateur> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: DetailsCommandes
        public async Task<IActionResult> Index()
        {
            return View(await _context.DetailsCommandes.Include(dc => dc.Produit).ToListAsync());
        }

        // GET: DetailsCommandes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailsCommande = await _context.DetailsCommandes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (detailsCommande == null)
            {
                return NotFound();
            }

            return View(detailsCommande);
        }

        // GET: DetailsCommandes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DetailsCommandes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PrixUnitaire,Quantite")] DetailsCommande detailsCommande)
        {
            if (ModelState.IsValid)
            {
                _context.Add(detailsCommande);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(detailsCommande);
        }

        // GET: DetailsCommandes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailsCommande = await _context.DetailsCommandes.Include(dc => dc.Commande).Where(dc => dc.Id == id).FirstAsync();
            if (detailsCommande == null)
            {
                return NotFound();
            }
            return View(detailsCommande);
        }

        // POST: DetailsCommandes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PrixUnitaire,Quantite")] DetailsCommande detailsCommande, int idCommande)
        {
            if (id != detailsCommande.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(detailsCommande);
                    _context.SaveChangesAsync().Wait();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DetailsCommandeExists(detailsCommande.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Details", "Commandes", new { id = idCommande });
            }
            return View(detailsCommande);
        }

        // GET: DetailsCommandes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var detailsCommande = await _context.DetailsCommandes.Include(dc => dc.Commande).Where(dc => dc.Id == id).FirstAsync();

            if (detailsCommande == null)
            {
                return NotFound();
            }

            return View(detailsCommande);
        }

        // POST: DetailsCommandes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id, int idCommande)
        {
            var detailsCommande = await _context.DetailsCommandes.FindAsync(id);
            _context.DetailsCommandes.Remove(detailsCommande);
            await _context.SaveChangesAsync();
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            var utilisateur = await _context.Utilisateurs.Include(u => u.Commandes).ThenInclude(c => c.DetailsCommandes).ThenInclude(dc => dc.Produit).Where(u => u.Id.Equals(idUtilisateur)).FirstAsync();
            utilisateur.Commandes.Last().CalculerTotal();
            _context.SaveChangesAsync().Wait();
            return RedirectToAction("Details", "Commandes", new { id = idCommande });
        }

        private bool DetailsCommandeExists(int id)
        {
            return _context.DetailsCommandes.Any(e => e.Id == id);
        }
    }
}

Groupement Citoyen/Views/Commandes/Create.cshtml
@model Groupement_Citoyen.Models.Commande

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Commande</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Groupement Citoyen/Views/Commandes/Delete.cshtml
@model Groupement_Citoyen.Models.Commande

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Commande</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAchat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAchat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Groupement Citoyen/Views/Commandes/Details.cshtml
@model Groupement_Citoyen.Models.Commande

@{
    ViewData["Title"] = "Details";
}

<h1>Details de votre commande</h1>
@if (!Model.Valider && Model.Total > 0)
{
    <form asp-action="ValiderCommande" asp-controller="Commandes" asp-route-idUtilisateur="@this.User.Identity">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <input type="submit" value="Valider votre commande" class="btn btn-light" />
        </div>
    </form>
}
<div>
    <h4>Commande</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateAchat)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateAchat)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.DetailsCommandes.Last().Produit)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DetailsCommandes.Last().PrixUnitaire)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DetailsCommandes.Last().Quantite)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DetailsCommandes.Last().Produit.Producteur)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (DetailsCommande dc in Model.DetailsCommandes)
            {
                <tr>
                    <td>
                        @dc.Produit.Nom
                    </td>
                    <td>
                        @dc.PrixUnitaire
                    </td>
                    <td>
                        @dc.Quantite
                    </td>
                    <td>
                        @dc.Produit.Producteur.NomComplet
                    </td>
                    @if (!Model.Valider)
                    {
                        <td>
                            <a asp-controller="DetailsCommandes" asp-action="Edit" asp-route-id="@dc.Id">Edit</a> |
                            <a asp-controller="DetailsCommandes" asp-action="Delete" asp-route-id="@dc.Id">Delete</a>
                        </td>
                    }
                </tr>

            }
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index">Vos commandes</a>
</div>

Groupement Citoyen/Views/Commandes/Edit.cshtml
@model Groupement_Citoyen.Models.Commande

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Commande</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="DateAchat" class="control-label"></label>
                <input asp-for="DateAchat" class="form-control" />
                <span asp-validation-for="DateAchat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Groupement Citoyen/Views/Commandes/Index.cshtml
@model Groupement_Citoyen.Models.Utilisateur

@{
    ViewData["Title"] = "Index";
}

<partial name="/Views/Utilisateurs/MontantPortefeuille.cshtml" />

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Commandes.First().DateAchat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Commandes.First().Total)
            </th>
            <th>
                Nombre de produits
            </th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Commandes)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.DateAchat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DetailsCommandes.Count)
                </td>
                <td> 
                    <a class="btn btn-light" asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
                <td>
                    @if (!item.Valider && item.Total > 0)
                    {
                        <form asp-action="ValiderCommande" asp-controller="Commandes" asp-route-idUtilisateur="@this.User.Identity">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <input type="submit" value="Valider votre commande" class="btn btn-light" />
                            </div>
                        </form>
                    }            
                </td>
            </tr>
        }
    </tbody>
</table>