Groupement Citoyen/Models/Utilisateur.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace Groupement_Citoyen.Models
{
    public class Utilisateur : IdentityUser
    {
        public Utilisateur() : base()
        {

        }
        public string Nom { get; set; }
        [DisplayName("Prénom")]
        public string Prenom { get; set; }
        [Range(0, 10000)]
        [DataType(DataType.Currency)]
        [DisplayName("Montant de votre portefeuille")]
        public decimal MontantPortefeuille { get; set; } = 0;
        public string Adresse { get; set; }
        public string NomComplet
        {
            get
            {
                return $"{this.Nom} {this.Prenom}";
            }
        }
        public List<Produit> Produits = new List<Produit>();
        public List<Commande> Commandes { get; set; } = new List<Commande>();
        public bool AjouterMontant(decimal montant)
        {
            if (montant <= 0) return false;
            MontantPortefeuille += montant;
            return true;
        }

        public void PayerCommande()
        {

            if (!Commandes.Last().Valider && (Commandes.Last().Total <= MontantPortefeuille))
            {
                MontantPortefeuille -= Commandes.Last().Total;
                foreach (DetailsCommande dc in Commandes.Last().DetailsCommandes)
                {
                    dc.Produit.Quantite -= dc.Quantite;
                }
                Commandes.Last().DateAchat = DateTime.Now;
                Commandes.Last().Valider = true;
                Commandes.Add(new Commande());
            }
        }
    }
}

Groupement Citoyen/Controllers/ProduitsController.cs
using Groupement_Citoyen.Models;
using Groupement_Citoyen.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Groupement_Citoyen.Controllers
{
    [Authorize(Roles ="Utilisateur, Producteur")]
    public class ProduitsController : Controller
    {
        private readonly GroupementCitoyenDbContext _context;
        private readonly UserManager<Utilisateur> _userManager;
        public ProduitsController(GroupementCitoyenDbContext context, UserManager<Utilisateur> userManager)
        {
            _context = context;
            _userManager = userManager;

        }

        // GET: Produits
        public async Task<IActionResult> Index(string idProducteur)
        {
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            Utilisateur utilisateur = await _userManager.FindByIdAsync(idUtilisateur);
            var roles = await _userManager.GetRolesAsync(utilisateur);
            if (roles.First().Contains("Producteur"))
            {
                return View(await _context.Produits.Include(p => p.Producteur).Where(p => p.Producteur.Id.Equals(idUtilisateur)).ToListAsync());
            }
            ViewBag.userId = idUtilisateur;
            if (idProducteur != null)
                return View(await _context.Produits.Include(p => p.Producteur).Where(p => p.Producteur.Id.Equals(idProducteur) && p.Visible).ToListAsync());
            return View(await _context.Produits.Include(p => p.Producteur).Where(p => p.Visible).ToListAsync());
        }

        // GET: Produits/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // GET: Produits/Create
        public async Task<IActionResult> Create()
        {
            ProduitCreationVM vm = new ProduitCreationVM()
            {
                Produit = new Produit(),
                Producteur = await _context.Utilisateurs.FirstOrDefaultAsync()
            };
            return View(vm);
        }

        // POST: Produits/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nom,Quantite,Prix,Description,Visible")] Produit produit)
        {
            string idProduteur = _userManager.GetUserId(HttpContext.User);
            produit.Producteur = await _context.Utilisateurs.Where(u => u.Id.Equals(idProduteur)).FirstAsync();
            if (ModelState.IsValid)
            {
                _context.Add(produit);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits.FindAsync(id);
            if (produit == null)
            {
                return NotFound();
            }
            return View(produit);
        }

        // POST: Produits/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Quantite,Prix,Description,Visible")] Produit produit)
        {
            if (id != produit.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produit);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduitExists(produit.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produit);
        }

        // GET: Produits/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produit = await _context.Produits
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produit == null)
            {
                return NotFound();
            }

            return View(produit);
        }

        // POST: Produits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produit = await _context.Produits.FindAsync(id);
            _context.Produits.Remove(produit);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduitExists(int id)
        {
            return _context.Produits.Any(e => e.Id == id);
        }
    }
}

Groupement Citoyen/Controllers/UtilisateursController.cs
using Groupement_Citoyen.Models;
using Groupement_Citoyen.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Groupement_Citoyen.Controllers
{
    [Authorize(Roles ="Responsable, Utilisateur")]
    public class UtilisateursController : Controller
    {
        private readonly GroupementCitoyenDbContext _context;
        private readonly UserManager<Utilisateur> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public UtilisateursController(GroupementCitoyenDbContext context, UserManager<Utilisateur> userManager, RoleManager<IdentityRole> roleManager, GroupementCitoyenDbContext groupementCitoyenDbContext)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Producteurs
        public async Task<IActionResult> Index()
        {
            var users = await _context.Utilisateurs.ToListAsync();
            List<UserRoleVM> result = new List<UserRoleVM>();
            foreach (Utilisateur u in users)
            {
                UserRoleVM userRole = new UserRoleVM();
                userRole.role = _userManager.GetRolesAsync(u).Result.First();
                if (userRole.role.Contains("Producteur"))
                {
                    userRole.utilisateur = u;
                    result.Add(userRole);
                }

            }
            return View(result);
        }


        // GET: Producteurs/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Producteurs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nom,Prenom, Adresse, Email")] Utilisateur utilisateur, string motDePasse)
        {
            if (ModelState.IsValid)
            {
                var user = _userManager.FindByEmailAsync(utilisateur.Email).Result;
                if (user == null)
                {
                    _userManager.CreateAsync(utilisateur, motDePasse).Wait();
                    _userManager.AddToRoleAsync(utilisateur, "Producteur").Wait();
                    _context.Add(utilisateur);
                    _context.SaveChangesAsync().Wait();

                }
                return RedirectToAction(nameof(Index));
            }
            return View(utilisateur);
        }

        // GET: Producteur/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var producteur = await _context.Utilisateurs.FindAsync(id);
            if (producteur == null)
            {
                return NotFound();
            }

            return View(producteur);
        }

        // POST: DetailsCommandes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            Utilisateur producteur = await _context.Utilisateurs.Where(u => u.Id.Equals(id)).FirstAsync();
            foreach (Produit produit in producteur.Produits)
            {
                _context.Remove(produit);
            }
            _context.Remove(producteur);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // POST: AjouterMontant
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjouterMontant(decimal montant)
        {
            string idUtilisateur = _userManager.GetUserId(HttpContext.User);
            var utilisateur = await _userManager.FindByIdAsync(idUtilisateur);
            utilisateur.AjouterMontant(montant);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Commandes");
        }
    }
}

Groupement Citoyen/Views/Utilisateurs/Create.cshtml
@model Groupement_Citoyen.Models.Utilisateur

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Producteur</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prenom" class="control-label"></label>
                <input asp-for="Prenom" class="form-control" />
                <span asp-validation-for="Prenom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Mot de passe</label>
                <input type="password" name="motDePasse" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Groupement Citoyen/Views/Utilisateurs/Delete.cshtml
@model Groupement_Citoyen.Models.Utilisateur

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Utilisateur</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Prenom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Prenom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Groupement Citoyen/Views/Utilisateurs/Index.cshtml
@model IEnumerable<Groupement_Citoyen.ViewModel.UserRoleVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    @if (this.User.IsInRole("Responsable"))
    {
        <a asp-action="Create">Create</a>
    }
    </p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.utilisateur.NomComplet)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.utilisateur.Adresse)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.utilisateur.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.utilisateur.Adresse)
            </td>
            <td>
                @if (this.User.IsInRole("Responsable"))
                {
                    <a asp-action="Delete" asp-route-id="@item.utilisateur.Id">Delete</a>
                }
                @if (this.User.IsInRole("Utilisateur"))
                {
                    <a asp-action="Index" asp-controller="Produits" asp-route-idUtilisateur="@item.utilisateur.Id">Ses produits</a>
                }
            </td>
        </tr>
        }
    </tbody>
</table>

Groupement Citoyen/Views/Utilisateurs/MontantPortefeuille.cshtml
@model Groupement_Citoyen.Models.Utilisateur
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<table>
    <tr>
        <td>
            @Html.DisplayNameFor(model => model.MontantPortefeuille) :
        </td>
        <td>
            @Html.DisplayFor(model => model.MontantPortefeuille)

        </td>
    </tr>

</table>

<form asp-action="AjouterMontant" asp-controller="Utilisateurs">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="@Model.Id" />
    <table>
        <tr>
            <td>
                <label class="control-label">Ajouter un montant :</label>
            </td>
            <td>
                <div class="form-group">
                    <input name="montant" class="form-control input-sm" />
                    <span asp-validation-for="@Model.MontantPortefeuille" class="text-danger"></span>
                </div>
            </td>
            <td>
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary " />
                </div>
            </td>
        </tr>

    </table>
    
</form>